### PR TITLE
Skipping existent Circuits

### PR DESCRIPTION
**Pull request by stroblme**
This PR introduces the skipping of generating circuits which already exist from a previous run as mentioned in #68 .
Specifically this is implemented by adding another node which runs mutually exclusive with the one that is generating the circuits.
The additional node only extracts information such as number of shots and the desired framework from the partition data and skips the generation of the corresponding circuit.

**Edit**: The same problem also applies for the latest implementation which calculates the entangling capability and expressiblity (measures). Thus this PR also adds skipping a redundant calculation of those measures if corresponding files exist.

This PR effectively touches `pipeline_registry.py`, `data_generation\nodes.py` and `data_generation\pipeline.py`.

~Merging will potentially result in conflicts because of the restructuring in #92 . Therefore, **merge #92 first and then check for conflicts here**.~

**This PR requires #92 and #102 being merged first!**

### CODE REVIEW

**Comment by stroblme** [comment]
Resolved merged conflicts

**Comment by stroblme** [comment]
Cleanups and same implementation for skipping previously calculated measures.

**Comment by stroblme** [comment]
> Hello @stroblme! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:
> 
>     * In the file [`src/quafel/pipelines/data_generation/nodes.py`](https://github.com/cirKITers/Quafel/blob/4c9053892aea880cd6de194557cd2756b0a6280a/src/quafel/pipelines/data_generation/nodes.py):
> 
> 
> > [Line 466:61](https://github.com/cirKITers/Quafel/blob/4c9053892aea880cd6de194557cd2756b0a6280a/src/quafel/pipelines/data_generation/nodes.py#L466): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> 
>     * In the file [`src/quafel/pipelines/data_generation/pipeline.py`](https://github.com/cirKITers/Quafel/blob/4c9053892aea880cd6de194557cd2756b0a6280a/src/quafel/pipelines/data_generation/pipeline.py):
> 
> 
> > [Line 115:89](https://github.com/cirKITers/Quafel/blob/4c9053892aea880cd6de194557cd2756b0a6280a/src/quafel/pipelines/data_generation/pipeline.py#L115): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 88 characters)
> > [Line 116:89](https://github.com/cirKITers/Quafel/blob/4c9053892aea880cd6de194557cd2756b0a6280a/src/quafel/pipelines/data_generation/pipeline.py#L116): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 88 characters)
> 
> ##### Comment last updated at 2024-06-07 11:54:25 UTC

ignoring pep as overwritten by black

**Review by cDenius — APPROVED** [review]
As discussed on June 10th, this is good to go :)

**Pull request merged**
