### PR TITLE
Entangling Capability and Expressibility

### LINKED ISSUE #47: measure entangling capability

### PR DESCRIPTION
**Pull request by stroblme**
This PR resolved #47 and #37.
The implementation includes:
- random circuits are first generated with unbound parameters (parameters are only bound before conversion to qasm). This was necessary, because the implementation of measures requires parameter adjustment
- implementation of the entangling capability following https://arxiv.org/abs/1905.10876
- implementation of the expressiblity following https://arxiv.org/abs/quant-ph/0305094 as *inverse* of the similarity of the state integral to the Haar measure
- both implementations of the measures were inspired by https://obliviateandsurrender.github.io/blogs/expr.html
- adding of 'samples_per_parameter' option in 'data_generation.yml' to the amount of sampled parameters when calculating the measures
- adding separate folder for storing the measures, so that in case something goes wrong, we don't have to start all-over again. This **will** result in different data locations but should not conflict with existent installations.
- adaption of the 'data generation' pipelines to include the nodes for calculating the measures
- adaption of the 'data science' pipeline to include the measures when combining evaluation results
- implementation of corresponding visualizations. Both measures result in a single figure using the standard color scheme.
- adaption of the 'data visualization' pipeline to include the nodes for generating the plots
- docstrings for all modified methods

After some evaluations and testing:
- added caching for both, Haar integrals and statevectors of circuits for each of the sampled parameter combinations which are identified using md5 hashes
- converted performance critical operations to jax->jit
- minor performance optimizations
- sort of hacky estimate how many samples we use for the pqc based on its parameters and number of qubits
- fixes in visualization
- updated overview diag accordingly

### CODE REVIEW

**Comment by stroblme** [comment]
> Hello @stroblme! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:
> 
>     * In the file [`src/quafel/pipelines/data_generation/nodes.py`](https://github.com/cirKITers/Quafel/blob/a85c147f0a4db880badf25f8d7b0de72b230bf23/src/quafel/pipelines/data_generation/nodes.py):
> 
> 
> > [Line 382:61](https://github.com/cirKITers/Quafel/blob/a85c147f0a4db880badf25f8d7b0de72b230bf23/src/quafel/pipelines/data_generation/nodes.py#L382): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> 
> ##### Comment last updated at 2024-03-25 14:32:37 UTC

ignoring, [because E203 is not PEP complient](https://github.com/psf/black/blob/06ccb88bf2bd35a4dc5d591bb296b5b299d07323/docs/guides/using_black_with_other_tools.md#flake8)

**Comment by stroblme** [comment]
Although the overhead by the JIT compilation slows down the computation in comparison to the numpy implementation, I observed fewer memory requirements and faster computation for 'n_qubits'>8.
Optimally we decide based on a threshold but this is probably over-engineering.

**Comment by cDenius** [comment]
Although there is some randomness in the calculation, you should be able to reproduce the results from your [source](https://obliviateandsurrender.github.io/blogs/expr.html), correct? Have you done that?

It would be a nice way to check your implementation.

**Comment by stroblme** [comment]
> Although there is some randomness in the calculation, you should be able to reproduce the results from your [source](https://obliviateandsurrender.github.io/blogs/expr.html), correct? Have you done that?
> 
> It would be a nice way to check your implementation.

Good point, will add that!

**Comment by stroblme** [comment]
Added some tests to verify reasonable values for expressibility and entangling capability as mentioned in #42

**Review by cDenius — APPROVED** [review]
Looks good Melvin!
Like the additions you made!
Go for it, buddy!

**Pull request merged**
